/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alumni;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.geom.AffineTransform;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author HP
 */
public class Edit_Alumni_ad extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    Connection con;
    ResultSet rs;
    PreparedStatement ps;
    PreparedStatement ps1;
    String ImgPath=null;
    public Edit_Alumni_ad() {
        // this.setExtendedState(MAXIMIZED_BOTH);
        
        initComponents();
        con = DBconnect.connect();
        
       
          try {
              ps=con.prepareStatement("select * from stud_reg where enroll_no=?");
              ps.setString(1,AdminBlog.value);
              rs=ps.executeQuery();
              if(rs.next())
              {
                  txt_first_name.setText(rs.getString(1));
                  txt_address.setText(rs.getString(5));
                  txt_middle_name.setText(rs.getString(2));
                  txt_last_name.setText(rs.getString(3));
                  txt_email.setText(rs.getString(7));
                  txt_enroll_no.setText(rs.getString((4)));
                  txt_profession.setText(rs.getString(14));
                  
                  txt_mob.setText(rs.getString(9));
                  String s1=rs.getString(6);
                  dc_dob.setDate(rs.getDate(8));
                  InputStream is=rs.getBinaryStream("image");
                BufferedImage img=ImageIO.read(is);
                BufferedImage outimg=new BufferedImage(img.getWidth(),img.getHeight(),BufferedImage.TYPE_INT_RGB);
                Graphics2D gd=outimg.createGraphics();
                float xScale=(float)img.getWidth()/outimg.getWidth();
                float yScale=(float)img.getHeight()/outimg.getHeight();
                AffineTransform at=AffineTransform.getScaleInstance(xScale,yScale);
                gd.drawRenderedImage(img, at);
                gd.dispose();
                Image image=outimg.getScaledInstance(l_image.getWidth(),l_image.getHeight(),Image.SCALE_SMOOTH);
                ImageIcon imageIcon=new ImageIcon(image);
                l_image.setIcon(imageIcon);
                  if(s1.equals("male"))
                  {
                     jrb_male.setSelected(true);
                     jrb_female.setSelected(false);
                  }
                  else
                  {
                      jrb_male.setSelected(false);
                     jrb_female.setSelected(true);
                     
                  }
                 cmb_dept.setSelectedItem(rs.getString(10));
                 cmb_year.setSelectedItem(rs.getString(11));
              }
              
          } catch (Exception ex) {
              Logger.getLogger(Edit_Alumni_ad.class.getName()).log(Level.SEVERE, null, ex);
          }
            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_address = new javax.swing.JTextArea();
        txt_middle_name = new javax.swing.JTextField();
        txt_first_name = new javax.swing.JTextField();
        txt_enroll_no = new javax.swing.JTextField();
        txt_last_name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jrb_female = new javax.swing.JRadioButton();
        jrb_male = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_mob = new javax.swing.JTextField();
        txt_profession = new javax.swing.JTextField();
        cmb_year = new javax.swing.JComboBox<>();
        dc_dob = new com.toedter.calendar.JDateChooser();
        cmb_dept = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        l_image = new javax.swing.JLabel();
        btn_choose_image = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 16)); // NOI18N
        jLabel1.setText("Middle Name");

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 16)); // NOI18N
        jLabel2.setText("Enrollment No");

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 16)); // NOI18N
        jLabel3.setText("First Name");

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 16)); // NOI18N
        jLabel4.setText("Last Name");

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 16)); // NOI18N
        jLabel5.setText("Address");

        txt_address.setColumns(20);
        txt_address.setRows(5);
        jScrollPane1.setViewportView(txt_address);

        txt_middle_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_middle_nameKeyTyped(evt);
            }
        });

        txt_first_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_first_nameKeyTyped(evt);
            }
        });

        txt_enroll_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_enroll_noKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_enroll_noKeyTyped(evt);
            }
        });

        txt_last_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_last_nameKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 16)); // NOI18N
        jLabel6.setText("Gender");

        buttonGroup1.add(jrb_female);
        jrb_female.setText("Female");

        buttonGroup1.add(jrb_male);
        jrb_male.setSelected(true);
        jrb_male.setText("Male");

        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 16)); // NOI18N
        jLabel7.setText("Email");

        jButton4.setText("Ok");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jrb_male, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jrb_female, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_email)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txt_first_name)
                                            .addComponent(txt_middle_name)
                                            .addComponent(txt_last_name)
                                            .addComponent(txt_enroll_no)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                                        .addGap(45, 45, 45)
                                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)))))
                        .addGap(149, 149, 149))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_first_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_middle_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_last_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_enroll_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrb_female)
                    .addComponent(jrb_male))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 16)); // NOI18N
        jLabel8.setText("Date of birth");

        jLabel9.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 16)); // NOI18N
        jLabel9.setText("Department name");

        jLabel10.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 16)); // NOI18N
        jLabel10.setText("Mobile no");

        jLabel11.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 16)); // NOI18N
        jLabel11.setText("Current Profession");

        jLabel13.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 16)); // NOI18N
        jLabel13.setText("Passout year");

        txt_mob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mobActionPerformed(evt);
            }
        });
        txt_mob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_mobKeyTyped(evt);
            }
        });

        txt_profession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_professionActionPerformed(evt);
            }
        });
        txt_profession.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_professionKeyTyped(evt);
            }
        });

        cmb_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", " " }));

        cmb_dept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer", "Electronics", "Civil" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(dc_dob, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_mob)
                            .addComponent(cmb_dept, 0, 314, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmb_year, 0, 314, Short.MAX_VALUE)
                            .addComponent(txt_profession)))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dc_dob, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_mob, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_profession, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(181, 181, 181))
        );

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni/Images/update10.png"))); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni/Images/return_arrow.png"))); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni/Images/exit.png"))); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 16)); // NOI18N
        jLabel16.setText("Image");

        l_image.setBackground(new java.awt.Color(204, 255, 255));
        l_image.setOpaque(true);

        btn_choose_image.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_choose_image.setText("Choose image");
        btn_choose_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_choose_imageActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni/Images/warning.gif"))); // NOI18N
        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_choose_image, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(l_image, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(l_image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_choose_image)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     AdminBlog b=new AdminBlog();
     b.setVisible(true);
     this.dispose();
     
     // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     con = DBconnect.connect();
      String s1=""+cmb_dept.getSelectedItem();
      String s2=""+cmb_year.getSelectedItem();
      try{
        if(txt_first_name.getText().equals("") || txt_middle_name.getText().equals("") || txt_last_name.getText().equals("") || txt_enroll_no.getText().equals("") || txt_address.getText().equals("") || txt_email.getText().equals("") || dc_dob.getDate()==null || (jrb_male.isSelected()==false && jrb_female.isSelected()==false) || txt_mob.getText().equals("") || txt_profession.getText().equals("") ||  cmb_dept.getSelectedItem()==null || cmb_year.getSelectedItem()==null )
        {
            JOptionPane.showMessageDialog(null,"All fields are required");
        }
         else if(ImgPath==null)
                {
                    ps=con.prepareStatement("update stud_reg set first_name=?,middle_name=?,last_name=?,enroll_no=?,address=?,gender=?,email=?,dob=?,mobile_no=?,dept=?,pass_year=?,profession=? where enroll_no=?");
                ps.setString(1,txt_first_name.getText());
                SimpleDateFormat dateformat=new SimpleDateFormat("yyyy-MM-dd");
                String dob=dateformat.format(dc_dob.getDate());
                ps.setString(8,dob);
                ps.setString(2,txt_middle_name.getText());
                ps.setString(3,txt_last_name.getText());
                ps.setString(4,txt_enroll_no.getText());
                ps.setString(5,txt_address.getText());
                ps.setString(7,txt_email.getText());
                ps.setString(9,txt_mob.getText());
              
               
                ps.setString(12,txt_profession.getText());
                ps.setString(10,s1);
                ps.setString(11,s2);
                ps.setString(13,txt_enroll_no.getText());
                
                 //   FileInputStream img=null;
                  // img=new FileInputStream(new File(ImgPath));
                  
                 //ps.setBlob(15, img);
                 
                 
                     
                 
                if(jrb_male.isSelected())
                {
                   ps.setString(6,"male");
                }
                else
                {
                    ps.setString(6,"female");
                }
               /* Date date1=dc_dob.getDate();
                String dates=new SimpleDateFormat("yyyy-MM-dd").format(date1);
                ps.setString(8,dates);*/
                ps.executeUpdate();
                ps=con.prepareStatement("update event_stud set stud_name=? where stud_id=?");
                 ps.setString(2,txt_enroll_no.getText());
                 ps.setString(1,txt_first_name.getText());
                  ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"Record updated successfully");
              this.dispose();
                
                
                }

       else
        {
            
               
                ps=con.prepareStatement("update stud_reg set first_name=?,middle_name=?,last_name=?,enroll_no=?,address=?,gender=?,email=?,dob=?,mobile_no=?,dept=?,pass_year=?,profession=?,image=? where enroll_no=?");
                ps.setString(1,txt_first_name.getText());
                SimpleDateFormat dateformat=new SimpleDateFormat("yyyy-MM-dd");
                String dob=dateformat.format(dc_dob.getDate());
                ps.setString(8,dob);
                ps.setString(2,txt_middle_name.getText());
                ps.setString(3,txt_last_name.getText());
                ps.setString(4,txt_enroll_no.getText());
                ps.setString(5,txt_address.getText());
                ps.setString(7,txt_email.getText());
                ps.setString(9,txt_mob.getText());
                
                ps.setString(12,txt_profession.getText());
                ps.setString(10,s1);
                ps.setString(11,s2);
                ps.setString(14,txt_enroll_no.getText());
                 //   FileInputStream img=null;
                  // img=new FileInputStream(new File(ImgPath));
                  
                 //ps.setBlob(15, img);
                 File imgfile=new File(ImgPath);
                 FileInputStream img=new FileInputStream(imgfile);
                 ps.setBinaryStream(13,(InputStream)img,(int)imgfile.length());
                if(jrb_male.isSelected())
                {
                   ps.setString(6,jrb_male.getText());
                }
                else
                {
                    ps.setString(6,jrb_female.getText());
                }
               /* Date date1=dc_dob.getDate();
                String dates=new SimpleDateFormat("yyyy-MM-dd").format(date1);
                ps.setString(8,dates);*/
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"Record updated successfully");
              
               this.dispose();
               
                
            
        }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
   public ImageIcon ResizeImage(String imagepath,byte[] pic)
    {
     ImageIcon myImage=null;
     if(imagepath!=null)
     {
         myImage=new ImageIcon(imagepath);
         ImgPath=imagepath;
     }else
     {
         myImage=new ImageIcon(pic);
         
     }
     Image img=myImage.getImage();
     Image img2=img.getScaledInstance(l_image.getWidth(),l_image.getHeight(),Image.SCALE_SMOOTH);
     ImageIcon image=new ImageIcon(img2);
     return image;
     
    }
    
    private void txt_mobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mobActionPerformed

    private void txt_professionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_professionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_professionActionPerformed

    private void txt_first_nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_first_nameKeyTyped
    Validation vd=new Validation();
        vd.char_validation(evt,txt_first_name);        // TODO add your handling code here:
    }//GEN-LAST:event_txt_first_nameKeyTyped

    private void txt_middle_nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_middle_nameKeyTyped
   Validation vd=new Validation();
        vd.char_validation(evt,txt_middle_name);        // TODO add your handling code here:
    }//GEN-LAST:event_txt_middle_nameKeyTyped

    private void txt_last_nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_last_nameKeyTyped
    Validation vd=new Validation();
        vd.char_validation(evt,txt_last_name);        // TODO add your handling code here:
    }//GEN-LAST:event_txt_last_nameKeyTyped

    private void txt_enroll_noKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_enroll_noKeyTyped
    Validation vd=new Validation();
        vd.num_validaion(evt, txt_enroll_no);        // TODO add your handling code here:
    }//GEN-LAST:event_txt_enroll_noKeyTyped

    private void txt_mobKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_mobKeyTyped
      Validation vd=new Validation();
      vd.num_validaion(evt, txt_mob);
     if(txt_mob.getText().length()==10)
     {
         evt.consume();
     }
// TODO add your handling code here:
    }//GEN-LAST:event_txt_mobKeyTyped

    private void txt_professionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_professionKeyTyped
    Validation vd=new Validation();
      vd.char_validation(evt, txt_profession);        // TODO add your handling code here:
    }//GEN-LAST:event_txt_professionKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    txt_address.setText("");
    txt_email.setText("");
    txt_enroll_no.setText("");
    txt_first_name.setText("");
    txt_last_name.setText("");
    txt_middle_name.setText("");
    txt_mob.setText("");
   
    dc_dob.setDate(null);
   
    txt_profession.setText("");
    cmb_dept.setSelectedItem(null);
    cmb_year.setSelectedItem(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_choose_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_choose_imageActionPerformed
         // TODO add your handling code here:
         JFileChooser file=new JFileChooser();
         file.setCurrentDirectory(new File(System.getProperty("user.home")));
         FileNameExtensionFilter filter=new FileNameExtensionFilter("*.image","jpg","png");
         file.addChoosableFileFilter(filter);
         int result=file.showSaveDialog(null);
         if(result==JFileChooser.APPROVE_OPTION)
         {
             File selectedFile=file.getSelectedFile();
             String path=selectedFile.getAbsolutePath();
             l_image.setIcon(ResizeImage(path,null));
             ImgPath=path;
         }
         else
         {
          System.out.println("No file selected");
         }
    }//GEN-LAST:event_btn_choose_imageActionPerformed

    private void txt_enroll_noKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_enroll_noKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_enroll_noKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      con = DBconnect.connect();
        if(txt_enroll_no.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please enter enrollment number");
        }
       
       
        {
          try {
              ps=con.prepareStatement("select * from stud_reg where enroll_no=?");
              ps.setString(1,txt_enroll_no.getText());
              rs=ps.executeQuery();
              if(rs.next())
              {
                  txt_first_name.setText(rs.getString(1));
                  txt_address.setText(rs.getString(5));
                  txt_middle_name.setText(rs.getString(2));
                  txt_last_name.setText(rs.getString(3));
                  txt_email.setText(rs.getString(7));
                  txt_profession.setText(rs.getString(14));
                  
                  txt_mob.setText(rs.getString(9));
                  String s1=rs.getString(6);
                  dc_dob.setDate(rs.getDate(8));
                  InputStream is=rs.getBinaryStream("image");
                BufferedImage img=ImageIO.read(is);
                BufferedImage outimg=new BufferedImage(img.getWidth(),img.getHeight(),BufferedImage.TYPE_INT_RGB);
                Graphics2D gd=outimg.createGraphics();
                float xScale=(float)img.getWidth()/outimg.getWidth();
                float yScale=(float)img.getHeight()/outimg.getHeight();
                AffineTransform at=AffineTransform.getScaleInstance(xScale,yScale);
                gd.drawRenderedImage(img, at);
                gd.dispose();
                Image image=outimg.getScaledInstance(l_image.getWidth(),l_image.getHeight(),Image.SCALE_SMOOTH);
                ImageIcon imageIcon=new ImageIcon(image);
                l_image.setIcon(imageIcon);

                  if(s1.equals("male"))
                  {
                     jrb_male.setSelected(false);
                     jrb_female.setSelected(true);
                  }
                  else
                  {
                      jrb_male.setSelected(true);
                     jrb_female.setSelected(false);
                     
                  }
                 cmb_dept.setSelectedItem(rs.getString(10));
                 cmb_year.setSelectedItem(rs.getString(11));
              }
              else
              {
                   JOptionPane.showMessageDialog(null,"Entered enrollment number is not exist");
              }
          } catch (Exception ex) {
              Logger.getLogger(Edit_Alumni_ad.class.getName()).log(Level.SEVERE, null, ex);
          }
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         if(txt_enroll_no.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Enter enroll number to delete");
        }
       else
        { try{
            ps1=con.prepareStatement("select * from stud_reg where enroll_no=?");
            ps1.setString(1,txt_enroll_no.getText());
            rs=ps1.executeQuery();
            if(!rs.next())
            {
                JOptionPane.showMessageDialog(null,"Entered enroll number is not exist");
            }
            else
            {
           
                
                ps=con.prepareStatement("delete from stud_reg where enroll_no=?");
                ps.setString(1,txt_enroll_no.getText());
                System.out.println("hi");
                ps.executeUpdate();
                 ps=con.prepareStatement("delete from event_stud where stud_id=?");
                ps.setString(1,txt_enroll_no.getText());
                System.out.println("hi");
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"Delete successfully");
                AdminBlog ad=new AdminBlog();
                ad.setVisible(true);
            }  
            } catch (SQLException ex) {
                 Logger.getLogger(Edit_Alumni_ad.class.getName()).log(Level.SEVERE, null, ex);
             }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit_Alumni_ad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit_Alumni_ad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit_Alumni_ad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit_Alumni_ad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit_Alumni_ad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_choose_image;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmb_dept;
    private javax.swing.JComboBox<String> cmb_year;
    private com.toedter.calendar.JDateChooser dc_dob;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jrb_female;
    private javax.swing.JRadioButton jrb_male;
    private javax.swing.JLabel l_image;
    private javax.swing.JTextArea txt_address;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_enroll_no;
    private javax.swing.JTextField txt_first_name;
    private javax.swing.JTextField txt_last_name;
    private javax.swing.JTextField txt_middle_name;
    private javax.swing.JTextField txt_mob;
    private javax.swing.JTextField txt_profession;
    // End of variables declaration//GEN-END:variables
}
