/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alumni;

import java.awt.Font;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

/**
 *
 * @author Harshada
 */
public class Your_ev extends javax.swing.JFrame {

    /**
     * Creates new form Your_ev
     */
    Connection con;
    PreparedStatement ps;
    ResultSet rs;
    
    public Your_ev() {
         this.setExtendedState(MAXIMIZED_BOTH);
        initComponents();
        con=DBconnect.connect();
        	/*String col[]={"Name","Date","Venue","Department","Aim"};
		DefaultTableModel dtm=new DefaultTableModel(null,col);
		JTable jt=new JTable(dtm);
		jt.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
		JScrollPane jsp=new JScrollPane(jt);
		this.add(jsp);
		jsp.setBounds(200,100,500,500);
		try
		{
			ps=con.prepareStatement("select * from event_s,");
			rs=ps.executeQuery();
			  while(rs.next())
			  {
				dtm.addRow(new Object[] {rs.getString("name"),rs.getDate("date"),rs.getString("venue"),rs.getString("dept"),rs.getString("aim"),rs.getBoolean("")});
			  } 
		}
		catch(Exception ex)
		{
			ex.printStackTrace();
		}  */
                
		/*JTable jt=new JTable(dtm);
		jt.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
		JScrollPane jsp=new JScrollPane(jt);
		this.add(jsp);
		jsp.setBounds(200,100,500,500);*/
                String col[]={"ID","Name","Date","Venue","Department","Aim","Time","Status"};
		DefaultTableModel dtm=new DefaultTableModel(null,col);
		try
		{
			ps=con.prepareStatement("select * from events where event_id in (select event_id from event_stud  where stud_id=?)");
			ps.setString(1,AlumniLogin.a_enroll);
                        rs=ps.executeQuery();
			  while(rs.next())
			  {
                              String s1=rs.getString("time");
                              String s2=rs.getString("c");
                              String s3=s1.concat(s2);
				dtm.addRow(new Object[] {rs.getInt("event_id"),rs.getString("name"),rs.getString("date"),rs.getString("venue"),rs.getString("dept"),rs.getString("aim"),s3,Boolean.TRUE});//,rs.getString("enroll_no"),rs.getString("address"),rs.getString("mobile_no"),rs.getString("dept")});
			  } 
                          
                         JTable jt = new JTable(dtm) {
                @Override
                public Class getColumnClass(int column) {
                    switch (column) {
                        case 0:
                            return Integer.class;
                        case 1:
                            return String.class;
                        case 2:
                            return String.class;
                        case 3:
                            return String.class;
                        case 4:
                            return String.class;
                        case 5:
                            return String.class;
                        case 6:
                            return String.class;
                        default:
                            return Boolean.class;
                    }
                }
            }; 
                         jt.getModel().addTableModelListener(new TableChanged());
            //jt.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            //jt.setBounds(50, 50, 1500, 1500);
             Font font = new Font("Calibri", Font.PLAIN,20);
                jt.setFont(font);
                jt.getAutoResizeMode();
                jt.setRowHeight(20);
            JScrollPane jsp = new JScrollPane(jt);
            this.add(jsp);
            jsp.setBounds(50, 50, 1500, 1500);
		}
		catch(Exception ex)
		{
			ex.printStackTrace();
		}
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jb_back.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jb_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni/Images/return_arrow.png"))); // NOI18N
        jb_back.setText("Back");
        jb_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(1039, Short.MAX_VALUE)
                .addComponent(jb_back, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(734, Short.MAX_VALUE)
                .addComponent(jb_back)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_backActionPerformed
        // TODO add your handling code here:
        // AlumniBlog ab=new AlumniBlog();
        AlumniBlog ab=new AlumniBlog();
        ab.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jb_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Your_ev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Your_ev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Your_ev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Your_ev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Your_ev().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_back;
    // End of variables declaration//GEN-END:variables
}
